# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: local-wsl_ubuntu_20.04-pool

steps:
- script: |
    export JAVA_HOME_8_X64=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  displayName: 'Set JAVA_HOME for OpenJDK 1.8'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  env:
    JAVA_HOME_8_X64: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
    # jdkSourceOption: 'LocalDirectory'
    # jdkFile: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
    # jdkDirectory: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
